name: 🗃️ Tenant Module
on:
  pull_request:
    paths: 
    - modules/tenant/**
    branches:
    - main
  push: 
    paths: 
    - modules/tenant/**
    branches:
    - main
  workflow_run:
    workflows: 
    - 🪄 Portal Module
    - 🍭 Shared Module
    branches: 
    - main
    types: 
    - completed
  workflow_dispatch:
    inputs:
      workspace:
        description: |
          Name of the tenant module instance.
          By default, if this is not set, the DUPLO_TENANT variable will be used.
        type: string
        required: false
      cmd:
        description: Command to run
        type: choice
        default: plan
        options:
        - plan
        - apply
        - destroy
concurrency: 
  group: tenant-${{ inputs.workspace || vars.DUPLO_TENANT }}
jobs:

  module:
    name: Tenant Module
    uses: ./.github/workflows/tf-module.yml
    secrets: inherit
    with:
      cmd: ${{ github.event_name == 'pull_request' && 'plan' || inputs.cmd || 'apply' }}
      module: tenant
      workspace: ${{ inputs.workspace || vars.DUPLO_TENANT }}

  reconcile_apps:
    name: Reconcile Apps
    if: github.event_name == 'push' || github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    needs: module
    strategy:
      matrix:
        repo:
        - name: npm-pipeline-example
          ref: main
    steps:
    # the app actually has permissions to trigger the repository_dispatch
    - name: Init Github App
      uses: actions/create-github-app-token@v1
      id: gha-app
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}
        repositories: ${{ matrix.repo.name }}
    - name: Dispatch Projects
      id: dispatch
      env:
        GITHUB_TOKEN: ${{ steps.gha-app.outputs.token }}
        DUPLO_TENANT: ${{ inputs.workspace || vars.DUPLO_TENANT }}
        REPO: ${{ matrix.repo.name }}
        REF: ${{ matrix.repo.ref }}
      run: |
        # GitHub CLI api
        # https://cli.github.com/manual/gh_api
        echo "Dispatching workflow for $REPO in $DUPLO_TENANT"
        gh auth status
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${GITHUB_REPOSITORY_OWNER}/${REPO}/actions/workflows/tf-module.yml/dispatches \
          -f "ref=${REF}" \
          -f "inputs[cmd]=apply" \
          -f "inputs[tag]=current" \
          -f "inputs[environment]=${DUPLO_TENANT}"
